### ISSUE TITLE
How to have file eval.bin?

### ISSUE THREAD

**Issue by lekhachuy08** [sunfish-shogi/sunfish4#1]
I've built the program "sunfish_usi".

I'm trying to run it, but it simply exits because there's no file eval.bin.
How can I have this file?

**Comment by ngocdaothanh** [comment]
@sunfish-shogi Is eval.bin a kind of opening book data file of Shogi? This file is not included in the source code of this project. Can you please comment where I can download this file?

**Comment by sunfish-shogi** [comment]
`eval.bin` is not published yet. I will upload it after work.

As a side note,

- `eval.bin` is parameters of evaluation function. You can generate by `sunfish_ln` .
- `book.bin` is opening-book data. You can generate by `sunfish_tools --gen-book`

**Comment by ngocdaothanh** [comment]
Thanks, could you publish both files please.

**Comment by sunfish-shogi** [comment]
I have created a release v0.1.0 which include newest `eval.bin` and `book.bin`.

https://github.com/sunfish-shogi/sunfish4/releases/tag/v0.1.0

**Comment by ngocdaothanh** [comment]
> eval.bin is parameters of evaluation function.

I intend to use sunfish4 in a smartphone app. eval.bin is 47MB, which is too big to load it all to memory of smartphone.

Is eval.bin supposed to be a big file? Is there a way to reduce its size?

If don't use eval.bin (by setting `MATERIAL_LEARNING_ONLY` flag to true), how will the strength of sunfish4 be affected?

**Comment by sunfish-shogi** [comment]
`MATERIAL_LEARNING_ONLY` is technique for dividing learning phases of materials and other parameters.
In playing (sunfish_uri or sunfish_csa), Sunfish needs both of materials(embedded in `src/search/eval/Material.hpp`) and `eval.bin`.

Elements of `eval.bin` are defined in `src/search/eval/FeatureVector.hpp`.
So, if part of parameters will be removed from `eval.bin` and `FeatureVector.hpp` and some related source codes, a lightweight player is generated.
However, it may be very weak player. What player level do your app targets?

By the way, some major Shogi apps have server side very strong computer player.
(ex: "Shogi Wars", "Shogi Quest")

**Comment by ngocdaothanh** [comment]
> What player level do your app targets?

Many thanks for the info. I only need a strong enough level (between beginner level and mid level). So my main aim is to reduce the size of eval.bin so that it's small enough to load to smartphone memory.

Can you please provide more info about how to reduce the size of eval.bin?

(book.bin is only 3MB, so it's small enough.)

**Comment by sunfish-shogi** [comment]
Generating lightweight version from current master branch, you need to know about details of Sunfish implementation.
So, I'm thinking of creating a sample of source code which includes eval.bin converter.

What size do you think acceptable total memory usage is?

**Comment by ngocdaothanh** [comment]
I think it's good if eval.bin can be reduced to about 10~20MB:
https://stackoverflow.com/questions/18675557/what-is-the-maximum-amount-of-ram-an-app-can-use

**Comment by sunfish-shogi** [comment]
I have created lightweight version as follows:

- Release of lightweight version (including small eval.bin):
https://github.com/sunfish-shogi/sunfish4/releases/tag/v0.1.0-light
- Branch of lightweight version:
https://github.com/sunfish-shogi/sunfish4/tree/light-eval
- Branch including eval.bin converter:
https://github.com/sunfish-shogi/sunfish4/tree/conv-light-eval

I have removed high-dimensional parameters, and generated lightweight eval.bin which is about 3.5 MB.
(See https://github.com/sunfish-shogi/sunfish4/commit/8bbc6ac6fa65fff812fdde374223785fc597e79d)

I have not tested strength of lightweight version accurately. But it may stronger than I thought.

Sunfish uses memory resource for mainly evaluation parameters(eval.bin) and opening book(book.bin) and transposition table(hash table).
So, reducing memory usage, you need to specify small size for transposition table. If you use USI interface, you need to set an USI option: `USI_Hash`. (See http://www.geocities.jp/shogidokoro/usi.html)

**Comment by sunfish-shogi** [comment]
By the way, I think that this page's talk is not suggest that Android always imposes memory limit.
https://stackoverflow.com/questions/18675557/what-is-the-maximum-amount-of-ram-an-app-can-use

And Sunfish is written by C++. So it will be not managed by garbage collection and built by NDK.

Recently, many high-graphics or high-performance apps are using very large memory resource.
I have developed Android/iOS app by cocos2d-x 4 years ago. And that app was using  more than 32MB, too.

Of course, it is preferable that memory usage is small. I think these are trade-off.
Fortunately, lightweight Sunfish4 has enough strength for beginner or intermediate.

**Comment by ngocdaothanh** [comment]
Thank you very much!

I'm creating a wrapper for React Native here:
https://github.com/lekhachuy08/react-native-sunfish4

**Comment by sunfish-shogi** [comment]
I wish I could develop Shogi app, too.
But I have no rich knowledge for modern GUI frameworks.

So, I'm interested in your app. I hope it will success.

Thank you for your contact.
If you have other any questions, please create new issue or reopen this issue.

**Comment by ngocdaothanh** [comment]
ありがとうございます！

Yeah nowadays it's easier to create apps, but it's also confusing because there are many frameworks. My favorite ones are: [Cordova](https://cordova.apache.org/), [React Native](https://facebook.github.io/react-native/), and [Flutter](https://flutter.io/).
